name: CI / CD pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get commit SHA
        id: commit_sha
        run: echo "::set-output name=COMMIT_SHA::$(git rev-parse --short HEAD)"
      - name: Build Docker images
        run: docker-compose -f docker-compose.yml --project-name ${{ vars.STACK_NAME }} build
      - name: Push Docker images
        run: docker-compose -f docker-compose.yml --project-name ${{ vars.STACK_NAME }} push

  deploy:
    if: github.ref == 'refs/heads/main'
    needs:
      - build
    runs-on:
      - self-hosted
    env:
      TAG: ${{ github.sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Shut down docker compose deployment
        continue-on-error: true
        run: docker-compose -f docker-compose-run.yml --project-name ${{ vars.STACK_NAME }} down
      - name: Start the updated docker compose deployment
        run: docker-compose -f docker-compose-run.yml --project-name ${{ vars.STACK_NAME }} up -d
